include: ["_pages"]
include: ["_post"]
include: ["_layouts"]
include: ["_site"]
title: DailyDoseofDee
description: > # this means to ignore newlines until "baseurl:"
  I'd like to think I'm interesting so hopefully you will too.
theme: jekyll-theme-merlot
plugins:
  - jekyll-feed
repository: desstuff.github.io/myblog
permalink: /:about/
permalink: /:2017-09-12 This Digital Stuff.md/
permalink: /:BlogPosts.md/
