title: DailyDoseofDee
description: > # this means to ignore newlines until "baseurl:"
  I'd like to think I'm interesting so hopefully you will too. Read my blog to find out.
theme: jekyll-theme-merlot
plugins:
  - jekyll-feed
