include: ["_pages"]
include: ["_posts"]
title: DailyDoseofDee
description: > # this means to ignore newlines until "baseurl:"
  I'd like to think I'm interesting so hopefully you will too.
theme: jekyll-theme-merlot
plugins:
  - jekyll-feed
permalink: /:about/
permalink: /:2017-09-12 This Digital Stuff/
